import type { Metadata } from "next";
import localFont from "next/font/local";
import { Afacad } from 'next/font/google';
import "./globals.css";
import dynamic from 'next/dynamic';

const DynamicErrorBoundary = dynamic(() => import('@/components/ErrorBoundary'), { ssr: false });

const zainFont = localFont({
  src: [
    {
      path: "./fonts/Zain-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Zain-Bold.ttf",  // Make sure this file exists
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-zain",
  display: "swap",
});

const afacad = Afacad({
  subsets: ['latin'],
  variable: '--font-afacad',
  display: 'swap',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zainFont.variable} ${afacad.variable} font-sans antialiased min-h-screen flex flex-col`}
      >
        <DynamicErrorBoundary>
          <main className="flex-grow flex flex-col">
            {children}
          </main>
        </DynamicErrorBoundary>
      </body>
    </html>
  );
}
