import type { Metadata } from "next";
import { Zain, Afacad } from 'next/font/google';
import "./globals.css";  // Make sure this import is present and correct
import dynamic from 'next/dynamic';
import Image from "next/image";
import bgGrowvy from "@/assets/bg-growvy.png"

const DynamicErrorBoundary = dynamic(() => import('@/components/ErrorBoundary'), { ssr: false });

const zainFont = Zain({
  subsets: ['latin'],
  variable: '--font-zain',
  display: 'swap',
  weight: ['400', '700'],
});

const afacad = Afacad({
  subsets: ['latin'],
  variable: '--font-afacad',
  display: 'swap',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${zainFont.variable} ${afacad.variable}`}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
